server:
  port: 8082
  servlet:
    context-path: /websocket

spring:
  #  thymeleaf:
  #    prefix: classpath:/templates/
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

    static-path-pattern: /static/**
