server:
  port: 8082
  servlet:
    context-path: /websocket

  tomcat:
    uri-encoding: UTF-8
    max-threads: 400
    max-connections: 20000

spring:
  #  thymeleaf:
  #    prefix: classpath:/templates/
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

    static-path-pattern: /static/**
